version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container_2
    restart: always
    environment:
      POSTGRES_USER: vitalik
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: petvally_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
